version: '3'

services:

  izing-rabbitmq:
    image: rabbitmq:3-management
    container_name: "izing-rabbitmq"
    restart: always
    env_file:
      - ./backend/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - $HOME/www/izing/database/rabbitmq/data/:/var/lib/rabbitmq/
      - $HOME/www/izing/database/rabbitmq/logs/:/var/log/rabbitmq/log
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbitmq_network

  izing-frontend:
    container_name: "izing-frontend"
    domainname: izing.aireset.com.br
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    env_file:
      - ./frontend/.env
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 42970:3003
    # command: /start_production
    volumes:
      - "./frontend:/usr/src/app"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - rabbitmq_network
    depends_on:
      - izing-rabbitmq

  izing-backend:
    container_name: "izing-backend"
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 42971:3000
      - 42972:3100
    # command: /start_production
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "./backend:/usr/src/app"
      - $HOME/www/izing/media:/usr/src/app/public
    networks:
      - rabbitmq_network
    depends_on:
      - izing-rabbitmq

networks:
  rabbitmq_network:
    driver: bridge