version: '3'

services:

  fixPermissionsPostregres:
    image: 'postgres:14'
    user: root
    command: chown -R 1001:1001 /var/lib/postgresql
    volumes:
      - ./izing/data/postgres:/var/lib/postgresql
  
  izing-postgres:
    image: 'postgres:14'
    container_name: izing-postgres
    hostname: izing-postgres
    restart: always
    stdin_open: true
    tty: true
    env_file:
      - ./backend/.env
    volumes:
      - ./izing/data/postgres:/var/lib/postgresql
    depends_on:
      - fixPermissionsPostregres
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - izing-network
  
  izing-pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: izing-pgadmin4
    hostname: izing-pgadmin4
    restart: always
    stdin_open: true
    tty: true
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@izing.io"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2021!"
    depends_on:
      - izing-postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - izing-network

  izing-redis:
    image: redis:alpine
    container_name: izing-redis
    hostname: izing-redis
    restart: always
    stdin_open: true
    tty: true
    env_file: ./backend/.env
    volumes:
      - ./izing/data/redis:/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - izing-network
  
  izing-rabbitmq:
    image: rabbitmq:3-management
    container_name: izing-rabbitmq
    hostname: izing-rabbitmq
    restart: always
    stdin_open: true
    tty: true
    env_file:
      - ./backend/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./izing/data/rabbitmq/data/:/var/lib/rabbitmq/
      - ./izing/data/rabbitmq/logs/:/var/log/rabbitmq/log
    networks:
      - izing-network

  izing-backend:
    container_name: izing-backend
    hostname: izing-backend
    build:
      context: ./backend
    env_file:
      - ./backend/.env
    restart: always
    stdin_open: true
    tty: true
    # ports:
      # - 3100:3100
      # - 3000:3000
    # command: /start_production
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "./backend:/usr/src/app"
      - ./izing/media:/usr/src/app/public
    networks:
      - izing-network
    depends_on:
      - izing-redis
      - izing-postgres
      - izing-rabbitmq
    # command: ['npx', 'exec', 'npm', 's', '-p', '3000', '-b', '0.0.0.0']
  
  izing-nginx:
    container_name: izing-nginx
    hostname: izing-nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
      # args:
      #   - DOMINIO_CLIENTE=${DOMINIO_CLIENTE}
    entrypoint: nginx -g "daemon off;"
    ports:
      - "8080:8080" #chatwoot
      # - "8081:8081" #wppconnect
      - "8082:8082" #pgadmin
      - "8083:8083" #redis
      - "8090:8090" #backend
      # - "5672:5672" #rabbitmq
      # - "15672:15672" #rabbitmq
    volumes:
      - ./izing/media:/opt/services/app/media
    depends_on:
      - izing-postgres
      - izing-pgadmin4
      - izing-redis
      - izing-rabbitmq
      - izing-backend
    networks:
      - izing-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  izing-network:
    driver: bridge