#!/bin/bash
echo  "Updating izing, please wait."
cd  ~
cd izing.io
git checkout master
git pull
cd backend
npm install
rm -rf dist
npm run build
npx sequelize db:migrate
pm2 restart all

echo  "Update finished. Enjoy!"
